[package]
name = "livekit-bin"
version = "0.2.0"
edition = "2018"
authors = ["stackinspector"]
license = "Apache-2.0"
repository = "https://github.com/Berylsoft/LiveKit"
# description
# readme

[[bin]]
name = "livekit"
path = "livekit.rs"

[[bin]]
name = "feedrec"
path = "feedrec.rs"

[dependencies]
tokio = { version = "1.12", features = ["full"] }
serde_json = "1.0"
log = "0.4"
log4rs = { version = "1.0", features = ["all_components"] }
structopt = "0.3"
# project
livekit-api = { path = "../api" }
livekit-feed = { path = "../feed", features = ["client"] }
livekit = { path = "../livekit" }
