[workspace]
members = [
    "api",
    "feed",
    "feed-storage",
    "feed-client",
    "flv",
    "hls",
    "stream",
    "livekit",
    "bin/feedrec",
    "bin/feed-dump",
    "bin/interactor",
]
