[workspace]
resolver = "2"
members = [
    "api",
    "feed",
    "livekit",
    "bin/log-config",
    "bin/feedrec",
    "bin/feed-dump",
    "bin/feed-reprod",
    "bin/interactor",
    "bin/stream-url-builder",
]
