[workspace]
members = [
    "api",
    "feed",
    "feed-storage",
    "feed-client",
    "stream-get",
    "stream-parse",
    "livekit",
    "bin/feedrec",
    "bin/feed-dump",
    "bin/interactor",
]
