[package]
name = "livekit-stream-parse"
version = "0.1.0"
edition = "2021"
# authors = ["stackinspector"]
# license = "Apache-2.0"
repository = "https://github.com/Berylsoft/LiveKit"
# description
# readme

[lib]
name = "livekit_stream_parse"
path = "lib.rs"

[dependencies]
