[package]
name = "livekit-feed"
version = "0.2.0"
edition = "2018"
authors = ["stackinspector"]
license = "Apache-2.0"
repository = "https://github.com/Berylsoft/LiveKit"
# readme

[lib]
name = "livekit_feed"
path = "lib.rs"

[dependencies]
hex = "0.4"
rand = "0.8"
chrono = "0.4"
bytes = "1.1"
log = "0.4"
# compress
brotli-decompressor = "2.3"
# bin
binrw = "0.8"
bytes-codec = { git = "https://github.com/Berylsoft/bytes-codec" }
# serde
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
# async
futures = "0.3"
tokio = { version = "1.12", features = ["full"] }
async-channel = "1.6"
# net
tokio-tungstenite = { version = "0.15", features = ["rustls-tls"] }
reqwest = { version = "0.11", default-features = false, features = ["rustls-tls", "stream"] }
# storage
sled = "0.34.7"
# project
livekit-api = { path = "../api" }

[dev-dependencies]
hex-literal = "0.3"
