[package]
name = "livekit-flv"
version = "0.1.0"
edition = "2018"
# authors = ["stackinspector"]
# license = "Apache-2.0"
repository = "https://github.com/Berylsoft/LiveKit"
# description
# readme

[lib]
name = "livekit_flv"
path = "lib.rs"

[dependencies]
