[package]
name = "livekit-feed-dump"
version = "0.2.0"
edition = "2018"
authors = ["stackinspector"]
license = "Apache-2.0"
repository = "https://github.com/Berylsoft/LiveKit"
# description
# readme

[lib]
name = "livekit_feed_dump"
path = "lib.rs"

[[bin]]
name = "feed-dump"
path = "main.rs"

[dependencies]
log = "0.4"
log4rs = { version = "1.0", features = ["all_components"] }
structopt = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rocksdb = { version = "0.16", default-features = false, features = ["lz4"] }
livekit-feed-client = { path = "../../feed-client" }
