[package]
name = "livekit-feed-dump"
version = "0.3.0"
edition = "2021"
authors = ["stackinspector"]
license = "Apache-2.0"
repository = "https://github.com/Berylsoft/LiveKit"
# description
# readme

[[bin]]
name = "feed-dump"
path = "main.rs"

[dependencies]
structopt = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
kvdump = { git = "https://github.com/Berylsoft/KVDump" }
livekit-feed = { path = "../../feed" }
