[package]
name = "livekit"
version = "0.2.0"
edition = "2018"
authors = ["stackinspector"]
license = "Apache-2.0"
repository = "https://github.com/Berylsoft/LiveKit"
description = "A range of scalable and portable utilities for Bilibili Live's hosts, post-production teams and viewers"
# readme

[lib]
name = "livekit"
path = "lib.rs"

[dependencies]
rand = "0.8"
chrono = "0.4"
bytes = "1.1"
log = "0.4"
# serde
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
# async
futures = "0.3"
tokio = { version = "1.12", features = ["full"] }
async-channel = "1.6"
# net
reqwest = { version = "0.11", default-features = false, features = ["rustls-tls", "stream"] }
# project
livekit-api = { path = "../api", default-features = false, features = ["info", "stream"] }
livekit-feed = { path = "../feed", features = ["client"] }

[dev-dependencies]
hex-literal = "0.3"
