[package]
name = "livekit"
version = "0.3.0"
edition = "2021"
authors = ["stackinspector"]
license = "Apache-2.0"
repository = "https://github.com/Berylsoft/LiveKit"
# description
# readme

[lib]
name = "livekit"
path = "lib.rs"

[[bin]]
name = "livekit"
path = "main.rs"

[dependencies]
env_logger = "0.9"
rand = "0.8"
bytes = "1.1"
chrono = "0.4"
log = "0.4"
structopt = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
toml = "0.5"
futures = "0.3"
tokio = { version = "1", features = ["full"] }
async-channel = "1.6"
livekit-api = { path = "../api", features = ["info", "stream"] }
livekit-feed = { path = "../feed", features = ["schema", "storage", "stream"] }

[dev-dependencies]
hex-literal = "0.3"
