[package]
name = "livekit-stream-url-builder"
version = "0.3.0"
edition = "2021"
authors = ["stackinspector"]
license = "MPL-2.0"
repository = "https://github.com/Berylsoft/LiveKit"
# description
# readme

[[bin]]
name = "livekit-stream-url-builder"
path = "main.rs"

[dependencies]
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
structopt = "0.3"
livekit-api = { path = "../../api", features = ["stream"] }
